environment:
  matrix:
  - nodejs_version: 4
  - nodejs_version: 5
  - nodejs_version: 6

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

platform:
  - x64

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off
